name: Extract ZIP File

on:
  workflow_dispatch:

jobs:
  extract-zip:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Extract ZIP file
        run: |
          unzip -o "portfolio-claudio-stadelmann.zip" -d ./
      
      - name: Commit extracted files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Extract portfolio ZIP contents" || echo "Nenhuma mudança"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
